version: '3'
services:
  webdav:
    image: bytemark/webdav
    restart: always
    ports:
      - "8050:80"
    environment:
      AUTH_TYPE: Digest
      USERNAME: ${USERNAME} 
      PASSWORD: ${PASSWORD} 
    volumes:
      - /media/nana/USB-Volume/dv/wdav:/varlib/dav
