---
services:
  rdesktop:
    image: lscr.io/linuxserver/rdesktop:ubuntu-kde
    container_name: rdesktop
    privileged: true
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1001
      - PGID=1002
      - TZ=Asia/Hong_Kong
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #optional
      - /home/nana/appdata/rdesktop/data:/config #optional
    ports:
      - 8389:3389
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
