version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SCANNER_EXTRACTOR: ffmpeg
    volumes:
      - "./data:/data"
      - "/var/lib/mpd/music/nasmusic:/music:ro"
